# Generated by Django 2.1 on 2018-08-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nationality_and_domestic_market', models.CharField(max_length=255)),
                ('age', models.PositiveSmallIntegerField()),
                ('location_market', models.CharField(max_length=255)),
                ('team', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Football', 'Football'), ('Rugby', 'Rugby'), ('Athletics', 'Athletics'), ('Cycling', 'Cycling'), ('Swimming', 'Swimming'), ('Gymnastics', 'Gymnastics'), ('Golf', 'Golf'), ('American Football', 'American Football'), ('Basketball', 'Basketball'), ('Baseball', 'Baseball'), ('College Football', 'College Football'), ('College Basketball', 'College Basketball'), ('Ice Hockey', 'Ice Hockey')], max_length=255)),
                ('marketability', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('optimal_campaign_time', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('market_transfer', models.BooleanField()),
                ('instagram', models.BigIntegerField()),
                ('twiter', models.BigIntegerField()),
            ],
        ),
    ]
