# Generated by Django 2.1 on 2018-08-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180826_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='nationality_and_domestic_market',
            new_name='domestic_market',
        ),
    ]
