# Generated by Django 2.1 on 2018-08-26 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180826_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='optimal_campaign_time',
            new_name='optimal_campaign',
        ),
    ]
