# Generated by Django 2.1 on 2018-08-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180826_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='instagram',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='twiter',
            field=models.PositiveIntegerField(),
        ),
    ]
