# Generated by Django 2.1 on 2018-09-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180904_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, verbose_name='Height (m)'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Weight (kg)'),
        ),
    ]
