# Generated by Django 2.1 on 2018-09-07 09:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180905_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='additional_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
