# Generated by Django 2.1 on 2018-09-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180907_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='team',
        ),
    ]
