# Generated by Django 2.1 on 2018-09-07 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180907_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='market_transfer',
        ),
    ]
