# Generated by Django 2.1 on 2018-09-08 15:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180908_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='additional_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
