# Generated by Django 2.1 on 2018-09-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20180908_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
