# Generated by Django 2.1 on 2018-09-12 17:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20180910_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='twiter',
            new_name='twitter',
        ),
        migrations.AddField(
            model_name='athlete',
            name='twitter_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
    ]
