# Generated by Django 2.1 on 2018-09-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20180912_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='international',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='athlete',
            name='photo',
            field=models.URLField(default='https://cdn.mkeda.me/athletes/img/no-avatar.png'),
        ),
    ]
