# Generated by Django 2.1 on 2018-09-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_athlete_youtube_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='photo',
            field=models.URLField(default='https://cdn.mkeda.me/athletes/img/no-avatar.png', max_length=600),
        ),
    ]
