# Generated by Django 2.1.2 on 2018-10-13 10:01

import core.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20181001_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteslist',
            name='athletes',
            field=models.ManyToManyField(related_name='athletes_lists', to='core.Athlete'),
        ),
        migrations.AlterField(
            model_name='athleteslist',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
