# Generated by Django 2.1.2 on 2018-10-16 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0035_auto_20181013_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaguesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('leagues', models.ManyToManyField(related_name='leagues_lists', to='core.League')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
