# Generated by Django 2.1.2 on 2018-10-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_athletefollower'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='hashtag',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
