# Generated by Django 2.1.2 on 2018-10-24 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_team_hashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athletefollower',
            name='athlete',
        ),
        migrations.RemoveField(
            model_name='athletefollower',
            name='user',
        ),
        migrations.DeleteModel(
            name='AthleteFollower',
        ),
    ]
