# Generated by Django 2.1.2 on 2018-10-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followed_leagues',
            field=models.ManyToManyField(blank=True, related_name='followers', to='core.League'),
        ),
        migrations.AddField(
            model_name='profile',
            name='followed_teams',
            field=models.ManyToManyField(blank=True, related_name='followers', to='core.Team'),
        ),
    ]
