# Generated by Django 2.1.2 on 2018-10-31 11:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20181025_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='wiki_views_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='league',
            name='wiki_views_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='team',
            name='wiki_views_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
