# Generated by Django 2.1.2 on 2018-11-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20181101_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='team',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
