# Generated by Django 2.1.2 on 2018-11-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20181107_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='photo',
            field=models.URLField(default='/static/img/no-avatar.png', max_length=600),
        ),
        migrations.AlterField(
            model_name='league',
            name='photo',
            field=models.URLField(default='/static/img/no-avatar.png', max_length=600),
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.URLField(default='/static/img/no-avatar.png', max_length=600),
        ),
    ]
