# Generated by Django 2.1.3 on 2018-12-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_team_company_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('never', 'Never')], default='daily', max_length=8),
        ),
    ]
