# Generated by Django 2.1.7 on 2019-03-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_teamarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamarticle',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teamarticle',
            name='description',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterUniqueTogether(
            name='teamarticle',
            unique_together={('title', 'publishedAt')},
        ),
    ]
