# Generated by Django 3.1.2 on 2020-10-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20190401_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='additional_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='photo',
            field=models.URLField(default='/static/img/no-avatar.png', max_length=600),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='site_views_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='twitter_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='wiki_views_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='youtube_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='league',
            name='additional_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='league',
            name='photo',
            field=models.URLField(default='/static/img/no-avatar.png', max_length=600),
        ),
        migrations.AlterField(
            model_name='league',
            name='site_views_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='league',
            name='twitter_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='league',
            name='wiki_views_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='league',
            name='youtube_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='team',
            name='additional_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='team',
            name='company_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.URLField(default='/static/img/no-avatar.png', max_length=600),
        ),
        migrations.AlterField(
            model_name='team',
            name='site_views_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='team',
            name='stock_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='team',
            name='wiki_views_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='team',
            name='youtube_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='teamarticle',
            name='url',
            field=models.URLField(max_length=512),
        ),
    ]
